#!/usr/bin/env node

/**
 * Embed sql.js WASM file as base64 for standalone binaries
 * This script reads sql-wasm.wasm and generates a TypeScript file with the embedded binary
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

console.log('🔧 Embedding sql.js WASM binary...');

// Read the WASM file
const wasmPath = join(rootDir, 'node_modules', 'sql.js', 'dist', 'sql-wasm.wasm');
const wasmBuffer = readFileSync(wasmPath);
const wasmBase64 = wasmBuffer.toString('base64');

const wasmSizeKB = (wasmBuffer.length / 1024).toFixed(2);
const base64SizeKB = (Buffer.from(wasmBase64).length / 1024).toFixed(2);

console.log(`📦 Original WASM size: ${wasmSizeKB} KB`);
console.log(`📦 Base64 encoded size: ${base64SizeKB} KB`);
console.log(`📈 Overhead: ${((base64SizeKB - wasmSizeKB) / wasmSizeKB * 100).toFixed(1)}%`);

// Ensure output directory exists
const outputDir = join(rootDir, 'src', 'storage', 'embedded');
mkdirSync(outputDir, { recursive: true });

// Generate TypeScript file with embedded WASM
const outputPath = join(outputDir, 'sql-wasm-embedded.ts');
const content = `/**
 * Auto-generated file containing embedded sql.js WASM binary
 * Generated on: ${new Date().toISOString()}
 * Original size: ${wasmSizeKB} KB
 * Base64 size: ${base64SizeKB} KB
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'yarn embed-wasm' to regenerate
 */

/**
 * sql.js WASM binary encoded as base64
 * This allows the WASM to be bundled into standalone binaries
 */
export const SQL_WASM_BASE64 = '${wasmBase64}';

/**
 * Convert base64 string to Uint8Array for sql.js initialization
 */
export function getWasmBinary(): Uint8Array {
  const binaryString = Buffer.from(SQL_WASM_BASE64, 'base64');
  return new Uint8Array(binaryString);
}
`;

writeFileSync(outputPath, content, 'utf-8');

console.log(`✅ Embedded WASM written to: ${outputPath}`);
console.log('📝 File can now be imported in Database.ts');
