/**
 * Built-in theme definitions
 *
 * These themes are embedded directly in the code to ensure they work
 * correctly in bundled binaries (Bun) where filesystem access is limited.
 *
 * User themes can be added to .mimir/themes/ and will be loaded dynamically at runtime.
 */

import type { ThemeJSON } from './theme-schema.js';

export const builtinThemes: Record<string, ThemeJSON> = {
  mimir: {
    name: 'Mimir',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#2E3440', fg: '#ECEFF4' },
      headerText: { fg: '#D8DEE9' },
      footerBg: { bg: '#3B4252' },
      footerText: { fg: '#4C566A' },
      inputPrompt: { fg: '#88C0D0' },
      inputText: { fg: '#ECEFF4' },
      autocompleteBg: { bg: '#3B4252' },
      autocompleteText: { fg: '#ECEFF4' },
      autocompleteSelectedBg: { bg: '#88C0D0', fg: '#2E3440' },
      autocompleteSelectedText: { fg: '#2E3440' },
      autocompleteHeaderText: { fg: '#88C0D0', bold: true },
      autocompleteFooterText: { fg: '#616E88' },
      autocompleteMoreIndicator: { fg: '#616E88' },
      modePlan: { fg: '#5E81AC' },
      modeAct: { fg: '#A3BE8C' },
      modeDiscuss: { fg: '#B48EAD' },
      userMessage: { fg: '#8FBCBB', bg: '#3B4252' },
      assistantMessage: { fg: '#81A1C1' },
      systemMessage: { fg: '#5E81AC', bg: '#2E3440' },
      keyword: { fg: '#81A1C1' },
      string: { fg: '#A3BE8C' },
      number: { fg: '#B48EAD' },
      comment: { fg: '#616E88' },
      function: { fg: '#88C0D0' },
      variable: { fg: '#D8DEE9' },
      success: { fg: '#A3BE8C' },
      warning: { fg: '#EBCB8B' },
      error: { fg: '#BF616A' },
      info: { fg: '#88C0D0' },
      statusIdle: { fg: '#616E88' },
      statusReasoning: { fg: '#88C0D0' },
      statusActing: { fg: '#A3BE8C' },
      statusObserving: { fg: '#81A1C1' },
      statusInterrupted: { fg: '#EBCB8B' },
      borderColor: { fg: '#4C566A' },
      wizardTitle: { fg: '#88C0D0' },
      wizardAccent: { fg: '#5E81AC' },
      paramDescription: { fg: '#8b95a8' },
      diffAddLine: { bg: '#A3BE8C', fg: '#FFFFFF' },
      diffRemoveLine: { bg: '#D08770', fg: '#FFFFFF' },
    },
  },
  'tokyo-night': {
    name: 'Tokyo Night',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#1a1b26', fg: '#c0caf5' },
      headerText: { fg: '#a9b1d6' },
      footerBg: { bg: '#16161e' },
      footerText: { fg: '#565f89' },
      inputPrompt: { fg: '#7dcfff' },
      inputText: { fg: '#c0caf5' },
      autocompleteBg: { bg: '#24283b' },
      autocompleteText: { fg: '#c0caf5' },
      autocompleteSelectedBg: { bg: '#7aa2f7', fg: '#1a1b26' },
      autocompleteSelectedText: { fg: '#1a1b26' },
      autocompleteHeaderText: { fg: '#7aa2f7', bold: true },
      autocompleteFooterText: { fg: '#565f89' },
      autocompleteMoreIndicator: { fg: '#565f89' },
      modePlan: { fg: '#7aa2f7' },
      modeAct: { fg: '#9ece6a' },
      modeDiscuss: { fg: '#bb9af7' },
      userMessage: { fg: '#7dcfff' },
      assistantMessage: { fg: '#7aa2f7' },
      systemMessage: { fg: '#e0af68' },
      keyword: { fg: '#bb9af7' },
      string: { fg: '#9ece6a' },
      number: { fg: '#ff9e64' },
      comment: { fg: '#565f89' },
      function: { fg: '#7aa2f7' },
      variable: { fg: '#c0caf5' },
      success: { fg: '#9ece6a' },
      warning: { fg: '#e0af68' },
      error: { fg: '#f7768e' },
      info: { fg: '#7aa2f7' },
      statusIdle: { fg: '#565f89' },
      statusReasoning: { fg: '#7dcfff' },
      statusActing: { fg: '#9ece6a' },
      statusObserving: { fg: '#7aa2f7' },
      statusInterrupted: { fg: '#e0af68' },
      borderColor: { fg: '#414868' },
      wizardTitle: { fg: '#7aa2f7' },
      wizardAccent: { fg: '#bb9af7' },
      paramDescription: { fg: '#565f89' },
      diffAddLine: { bg: '#9ece6a', fg: '#1a1b26' },
      diffRemoveLine: { bg: '#f7768e', fg: '#c0caf5' },
    },
  },
  dracula: {
    name: 'Dracula',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#282A36', fg: '#F8F8F2' },
      headerText: { fg: '#F8F8F2' },
      footerBg: { bg: '#44475A' },
      footerText: { fg: '#6272A4' },
      inputPrompt: { fg: '#8BE9FD' },
      inputText: { fg: '#F8F8F2' },
      autocompleteBg: { bg: '#44475A' },
      autocompleteText: { fg: '#F8F8F2' },
      autocompleteSelectedBg: { bg: '#BD93F9', fg: '#282A36' },
      autocompleteSelectedText: { fg: '#282A36' },
      autocompleteHeaderText: { fg: '#BD93F9', bold: true },
      autocompleteFooterText: { fg: '#6272A4' },
      autocompleteMoreIndicator: { fg: '#6272A4' },
      modePlan: { fg: '#BD93F9' },
      modeAct: { fg: '#50FA7B' },
      modeDiscuss: { fg: '#FF79C6' },
      userMessage: { fg: '#8BE9FD' },
      assistantMessage: { fg: '#BD93F9' },
      systemMessage: { fg: '#F1FA8C' },
      keyword: { fg: '#FF79C6' },
      string: { fg: '#50FA7B' },
      number: { fg: '#FFB86C' },
      comment: { fg: '#6272A4' },
      function: { fg: '#F1FA8C' },
      variable: { fg: '#F8F8F2' },
      success: { fg: '#50FA7B' },
      warning: { fg: '#F1FA8C' },
      error: { fg: '#FF5555' },
      info: { fg: '#8BE9FD' },
      statusIdle: { fg: '#6272A4' },
      statusReasoning: { fg: '#8BE9FD' },
      statusActing: { fg: '#50FA7B' },
      statusObserving: { fg: '#BD93F9' },
      statusInterrupted: { fg: '#F1FA8C' },
      borderColor: { fg: '#44475A' },
      wizardTitle: { fg: '#BD93F9' },
      wizardAccent: { fg: '#FF79C6' },
      paramDescription: { fg: '#6272A4' },
      diffAddLine: { bg: '#50FA7B', fg: '#282A36' },
      diffRemoveLine: { bg: '#FF5555', fg: '#F8F8F2' },
    },
  },
  'catppuccin-mocha': {
    name: 'Catppuccin Mocha',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#1e1e2e', fg: '#cdd6f4' },
      headerText: { fg: '#bac2de' },
      footerBg: { bg: '#181825' },
      footerText: { fg: '#6c7086' },
      inputPrompt: { fg: '#89dceb' },
      inputText: { fg: '#cdd6f4' },
      autocompleteBg: { bg: '#181825' },
      autocompleteText: { fg: '#cdd6f4' },
      autocompleteSelectedBg: { bg: '#89b4fa', fg: '#1e1e2e' },
      autocompleteSelectedText: { fg: '#1e1e2e' },
      autocompleteHeaderText: { fg: '#89b4fa', bold: true },
      autocompleteFooterText: { fg: '#6c7086' },
      autocompleteMoreIndicator: { fg: '#6c7086' },
      modePlan: { fg: '#89b4fa' },
      modeAct: { fg: '#a6e3a1' },
      modeDiscuss: { fg: '#cba6f7' },
      userMessage: { fg: '#94e2d5' },
      assistantMessage: { fg: '#89b4fa' },
      systemMessage: { fg: '#f9e2af' },
      keyword: { fg: '#cba6f7' },
      string: { fg: '#a6e3a1' },
      number: { fg: '#fab387' },
      comment: { fg: '#6c7086' },
      function: { fg: '#89b4fa' },
      variable: { fg: '#cdd6f4' },
      success: { fg: '#a6e3a1' },
      warning: { fg: '#f9e2af' },
      error: { fg: '#f38ba8' },
      info: { fg: '#89b4fa' },
      statusIdle: { fg: '#6c7086' },
      statusReasoning: { fg: '#89dceb' },
      statusActing: { fg: '#a6e3a1' },
      statusObserving: { fg: '#89b4fa' },
      statusInterrupted: { fg: '#f9e2af' },
      borderColor: { fg: '#45475a' },
      wizardTitle: { fg: '#89b4fa' },
      wizardAccent: { fg: '#cba6f7' },
      paramDescription: { fg: '#6c7086' },
      diffAddLine: { bg: '#a6e3a1', fg: '#1e1e2e' },
      diffRemoveLine: { bg: '#f38ba8', fg: '#cdd6f4' },
    },
  },
  'catppuccin-latte': {
    name: 'Catppuccin Latte',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#eff1f5', fg: '#4c4f69' },
      headerText: { fg: '#5c5f77' },
      footerBg: { bg: '#e6e9ef' },
      footerText: { fg: '#9ca0b0' },
      inputPrompt: { fg: '#04a5e5' },
      inputText: { fg: '#4c4f69' },
      autocompleteBg: { bg: '#e6e9ef' },
      autocompleteText: { fg: '#4c4f69' },
      autocompleteSelectedBg: { bg: '#1e66f5', fg: '#eff1f5' },
      autocompleteSelectedText: { fg: '#eff1f5' },
      autocompleteHeaderText: { fg: '#1e66f5', bold: true },
      autocompleteFooterText: { fg: '#9ca0b0' },
      autocompleteMoreIndicator: { fg: '#9ca0b0' },
      modePlan: { fg: '#1e66f5' },
      modeAct: { fg: '#40a02b' },
      modeDiscuss: { fg: '#8839ef' },
      userMessage: { fg: '#179299' },
      assistantMessage: { fg: '#1e66f5' },
      systemMessage: { fg: '#df8e1d' },
      keyword: { fg: '#8839ef' },
      string: { fg: '#40a02b' },
      number: { fg: '#fe640b' },
      comment: { fg: '#9ca0b0' },
      function: { fg: '#1e66f5' },
      variable: { fg: '#4c4f69' },
      success: { fg: '#40a02b' },
      warning: { fg: '#df8e1d' },
      error: { fg: '#d20f39' },
      info: { fg: '#1e66f5' },
      statusIdle: { fg: '#9ca0b0' },
      statusReasoning: { fg: '#04a5e5' },
      statusActing: { fg: '#40a02b' },
      statusObserving: { fg: '#1e66f5' },
      statusInterrupted: { fg: '#df8e1d' },
      borderColor: { fg: '#ccd0da' },
      wizardTitle: { fg: '#1e66f5' },
      wizardAccent: { fg: '#8839ef' },
      paramDescription: { fg: '#9ca0b0' },
      diffAddLine: { bg: '#40a02b', fg: '#eff1f5' },
      diffRemoveLine: { bg: '#d20f39', fg: '#4c4f69' },
    },
  },
  'gruvbox-dark': {
    name: 'Gruvbox Dark',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#282828', fg: '#ebdbb2' },
      headerText: { fg: '#d5c4a1' },
      footerBg: { bg: '#3c3836' },
      footerText: { fg: '#928374' },
      inputPrompt: { fg: '#83a598' },
      inputText: { fg: '#ebdbb2' },
      autocompleteBg: { bg: '#3c3836' },
      autocompleteText: { fg: '#ebdbb2' },
      autocompleteSelectedBg: { bg: '#458588', fg: '#ebdbb2' },
      autocompleteSelectedText: { fg: '#ebdbb2' },
      autocompleteHeaderText: { fg: '#83a598', bold: true },
      autocompleteFooterText: { fg: '#928374' },
      autocompleteMoreIndicator: { fg: '#928374' },
      modePlan: { fg: '#83a598' },
      modeAct: { fg: '#b8bb26' },
      modeDiscuss: { fg: '#d3869b' },
      userMessage: { fg: '#8ec07c' },
      assistantMessage: { fg: '#83a598' },
      systemMessage: { fg: '#fabd2f' },
      keyword: { fg: '#d3869b' },
      string: { fg: '#b8bb26' },
      number: { fg: '#fe8019' },
      comment: { fg: '#928374' },
      function: { fg: '#83a598' },
      variable: { fg: '#ebdbb2' },
      success: { fg: '#b8bb26' },
      warning: { fg: '#fabd2f' },
      error: { fg: '#fb4934' },
      info: { fg: '#83a598' },
      statusIdle: { fg: '#928374' },
      statusReasoning: { fg: '#8ec07c' },
      statusActing: { fg: '#b8bb26' },
      statusObserving: { fg: '#83a598' },
      statusInterrupted: { fg: '#fabd2f' },
      borderColor: { fg: '#504945' },
      wizardTitle: { fg: '#83a598' },
      wizardAccent: { fg: '#458588' },
      paramDescription: { fg: '#928374' },
      diffAddLine: { bg: '#b8bb26', fg: '#282828' },
      diffRemoveLine: { bg: '#fb4934', fg: '#ebdbb2' },
    },
  },
  'gruvbox-light': {
    name: 'Gruvbox Light',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#fbf1c7', fg: '#3c3836' },
      headerText: { fg: '#504945' },
      footerBg: { bg: '#ebdbb2' },
      footerText: { fg: '#928374' },
      inputPrompt: { fg: '#076678' },
      inputText: { fg: '#3c3836' },
      autocompleteBg: { bg: '#ebdbb2' },
      autocompleteText: { fg: '#3c3836' },
      autocompleteSelectedBg: { bg: '#076678', fg: '#fbf1c7' },
      autocompleteSelectedText: { fg: '#fbf1c7' },
      autocompleteHeaderText: { fg: '#076678', bold: true },
      autocompleteFooterText: { fg: '#928374' },
      autocompleteMoreIndicator: { fg: '#928374' },
      modePlan: { fg: '#076678' },
      modeAct: { fg: '#79740e' },
      modeDiscuss: { fg: '#8f3f71' },
      userMessage: { fg: '#427b58' },
      assistantMessage: { fg: '#076678' },
      systemMessage: { fg: '#b57614' },
      keyword: { fg: '#8f3f71' },
      string: { fg: '#79740e' },
      number: { fg: '#af3a03' },
      comment: { fg: '#928374' },
      function: { fg: '#076678' },
      variable: { fg: '#3c3836' },
      success: { fg: '#79740e' },
      warning: { fg: '#b57614' },
      error: { fg: '#9d0006' },
      info: { fg: '#076678' },
      statusIdle: { fg: '#928374' },
      statusReasoning: { fg: '#427b58' },
      statusActing: { fg: '#79740e' },
      statusObserving: { fg: '#076678' },
      statusInterrupted: { fg: '#b57614' },
      borderColor: { fg: '#d5c4a1' },
      wizardTitle: { fg: '#076678' },
      wizardAccent: { fg: '#076678' },
      paramDescription: { fg: '#928374' },
      diffAddLine: { bg: '#79740e', fg: '#fbf1c7' },
      diffRemoveLine: { bg: '#9d0006', fg: '#3c3836' },
    },
  },
  dark: {
    name: 'Dark',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#1a1a1a', fg: '#ffffff' },
      headerText: { fg: '#e0e0e0' },
      footerBg: { bg: '#2d2d2d' },
      footerText: { fg: '#888888' },
      inputPrompt: { fg: '#00d4ff' },
      inputText: { fg: '#ffffff' },
      autocompleteBg: { bg: '#2d2d2d' },
      autocompleteText: { fg: '#ffffff' },
      autocompleteSelectedBg: { bg: '#00d4ff', fg: '#000000' },
      autocompleteSelectedText: { fg: '#000000' },
      autocompleteHeaderText: { fg: '#00d4ff', bold: true },
      autocompleteFooterText: { fg: '#666666' },
      autocompleteMoreIndicator: { fg: '#666666' },
      modePlan: { fg: '#2196F3' },
      modeAct: { fg: '#4CAF50' },
      modeDiscuss: { fg: '#C792EA' },
      userMessage: { fg: '#4CAF50', bg: '#2d2d2d' },
      assistantMessage: { fg: '#2196F3' },
      systemMessage: { fg: '#FF9800', bg: '#1a1a1a' },
      keyword: { fg: '#C792EA' },
      string: { fg: '#C3E88D' },
      number: { fg: '#F78C6C' },
      comment: { fg: '#546E7A' },
      function: { fg: '#82AAFF' },
      variable: { fg: '#EEFFFF' },
      success: { fg: '#4CAF50' },
      warning: { fg: '#FFC107' },
      error: { fg: '#F44336' },
      info: { fg: '#2196F3' },
      statusIdle: { fg: '#666666' },
      statusReasoning: { fg: '#00d4ff' },
      statusActing: { fg: '#4CAF50' },
      statusObserving: { fg: '#2196F3' },
      statusInterrupted: { fg: '#FFC107' },
      borderColor: { fg: '#444444' },
      wizardTitle: { fg: '#00d4ff' },
      wizardAccent: { fg: '#2196F3' },
      paramDescription: { fg: '#888888' },
      diffAddLine: { bg: '#22863a', fg: '#ffffff' },
      diffRemoveLine: { bg: '#cb2431', fg: '#ffffff' },
    },
  },
  light: {
    name: 'Light',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#f5f5f5', fg: '#000000' },
      headerText: { fg: '#424242' },
      footerBg: { bg: '#e0e0e0' },
      footerText: { fg: '#757575' },
      inputPrompt: { fg: '#0288D1' },
      inputText: { fg: '#212121' },
      autocompleteBg: { bg: '#e0e0e0' },
      autocompleteText: { fg: '#212121' },
      autocompleteSelectedBg: { bg: '#0288D1', fg: '#ffffff' },
      autocompleteSelectedText: { fg: '#ffffff' },
      autocompleteHeaderText: { fg: '#0288D1', bold: true },
      autocompleteFooterText: { fg: '#9E9E9E' },
      autocompleteMoreIndicator: { fg: '#9E9E9E' },
      modePlan: { fg: '#1565C0' },
      modeAct: { fg: '#2E7D32' },
      modeDiscuss: { fg: '#7B1FA2' },
      userMessage: { fg: '#2E7D32' },
      assistantMessage: { fg: '#1565C0' },
      systemMessage: { fg: '#EF6C00' },
      keyword: { fg: '#7B1FA2' },
      string: { fg: '#558B2F' },
      number: { fg: '#D84315' },
      comment: { fg: '#9E9E9E' },
      function: { fg: '#1976D2' },
      variable: { fg: '#424242' },
      success: { fg: '#2E7D32' },
      warning: { fg: '#F57C00' },
      error: { fg: '#C62828' },
      info: { fg: '#1565C0' },
      statusIdle: { fg: '#9E9E9E' },
      statusReasoning: { fg: '#0288D1' },
      statusActing: { fg: '#2E7D32' },
      statusObserving: { fg: '#1565C0' },
      statusInterrupted: { fg: '#F57C00' },
      borderColor: { fg: '#BDBDBD' },
      wizardTitle: { fg: '#0288D1' },
      wizardAccent: { fg: '#1565C0' },
      paramDescription: { fg: '#757575' },
      diffAddLine: { bg: '#d1f4d1', fg: '#000000' },
      diffRemoveLine: { bg: '#ffeef0', fg: '#000000' },
    },
  },
  'dark-colorblind': {
    name: 'Dark Colorblind',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#1a1a1a', fg: '#ffffff' },
      headerText: { fg: '#e0e0e0' },
      footerBg: { bg: '#2d2d2d' },
      footerText: { fg: '#888888' },
      inputPrompt: { fg: '#64B5F6' },
      inputText: { fg: '#ffffff' },
      autocompleteBg: { bg: '#2d2d2d' },
      autocompleteText: { fg: '#ffffff' },
      autocompleteSelectedBg: { bg: '#64B5F6', fg: '#000000' },
      autocompleteSelectedText: { fg: '#000000' },
      autocompleteHeaderText: { fg: '#64B5F6', bold: true },
      autocompleteFooterText: { fg: '#757575' },
      autocompleteMoreIndicator: { fg: '#757575' },
      modePlan: { fg: '#64B5F6' },
      modeAct: { fg: '#81C784' },
      modeDiscuss: { fg: '#9575CD' },
      userMessage: { fg: '#64B5F6' },
      assistantMessage: { fg: '#FFB74D' },
      systemMessage: { fg: '#9575CD' },
      keyword: { fg: '#E1BEE7' },
      string: { fg: '#FFE082' },
      number: { fg: '#FFAB91' },
      comment: { fg: '#757575' },
      function: { fg: '#90CAF9' },
      variable: { fg: '#E0E0E0' },
      success: { fg: '#81C784' },
      warning: { fg: '#FFB74D' },
      error: { fg: '#E57373' },
      info: { fg: '#64B5F6' },
      statusIdle: { fg: '#757575' },
      statusReasoning: { fg: '#64B5F6' },
      statusActing: { fg: '#81C784' },
      statusObserving: { fg: '#90CAF9' },
      statusInterrupted: { fg: '#FFB74D' },
      borderColor: { fg: '#424242' },
      wizardTitle: { fg: '#64B5F6' },
      wizardAccent: { fg: '#90CAF9' },
      paramDescription: { fg: '#888888' },
      diffAddLine: { bg: '#1976D2', fg: '#ffffff' },
      diffRemoveLine: { bg: '#EF6C00', fg: '#ffffff' },
    },
  },
  'light-colorblind': {
    name: 'Light Colorblind',
    supportsFullColor: true,
    colors: {
      headerBg: { bg: '#f5f5f5', fg: '#000000' },
      headerText: { fg: '#424242' },
      footerBg: { bg: '#e0e0e0' },
      footerText: { fg: '#757575' },
      inputPrompt: { fg: '#1976D2' },
      inputText: { fg: '#212121' },
      autocompleteBg: { bg: '#e0e0e0' },
      autocompleteText: { fg: '#212121' },
      autocompleteSelectedBg: { bg: '#1976D2', fg: '#ffffff' },
      autocompleteSelectedText: { fg: '#ffffff' },
      autocompleteHeaderText: { fg: '#1976D2', bold: true },
      autocompleteFooterText: { fg: '#9E9E9E' },
      autocompleteMoreIndicator: { fg: '#9E9E9E' },
      modePlan: { fg: '#1976D2' },
      modeAct: { fg: '#388E3C' },
      modeDiscuss: { fg: '#7B1FA2' },
      userMessage: { fg: '#1976D2' },
      assistantMessage: { fg: '#F57C00' },
      systemMessage: { fg: '#7B1FA2' },
      keyword: { fg: '#8E24AA' },
      string: { fg: '#F9A825' },
      number: { fg: '#D84315' },
      comment: { fg: '#9E9E9E' },
      function: { fg: '#1565C0' },
      variable: { fg: '#424242' },
      success: { fg: '#388E3C' },
      warning: { fg: '#F57C00' },
      error: { fg: '#D32F2F' },
      info: { fg: '#1976D2' },
      statusIdle: { fg: '#9E9E9E' },
      statusReasoning: { fg: '#1976D2' },
      statusActing: { fg: '#388E3C' },
      statusObserving: { fg: '#1565C0' },
      statusInterrupted: { fg: '#F57C00' },
      borderColor: { fg: '#BDBDBD' },
      wizardTitle: { fg: '#1976D2' },
      wizardAccent: { fg: '#1565C0' },
      paramDescription: { fg: '#757575' },
      diffAddLine: { bg: '#BBDEFB', fg: '#000000' },
      diffRemoveLine: { bg: '#FFE0B2', fg: '#000000' },
    },
  },
  'dark-ansi': {
    name: 'Dark ANSI',
    supportsFullColor: false,
    colors: {
      headerBg: { bg: '#000000', fg: '#FFFFFF' },
      headerText: { fg: '#FFFFFF' },
      footerBg: { bg: '#000000' },
      footerText: { fg: '#808080' },
      inputPrompt: { fg: '#00FFFF' },
      inputText: { fg: '#FFFFFF' },
      autocompleteBg: { bg: '#000000' },
      autocompleteText: { fg: '#FFFFFF' },
      autocompleteSelectedBg: { bg: '#00FFFF', fg: '#000000' },
      autocompleteSelectedText: { fg: '#000000' },
      autocompleteHeaderText: { fg: '#00FFFF', bold: true },
      autocompleteFooterText: { fg: '#808080' },
      autocompleteMoreIndicator: { fg: '#808080' },
      modePlan: { fg: '#0000FF' },
      modeAct: { fg: '#00FF00' },
      modeDiscuss: { fg: '#FF00FF' },
      userMessage: { fg: '#00FF00' },
      assistantMessage: { fg: '#0000FF' },
      systemMessage: { fg: '#FFFF00' },
      keyword: { fg: '#FF00FF' },
      string: { fg: '#00FF00' },
      number: { fg: '#FF0000' },
      comment: { fg: '#808080' },
      function: { fg: '#0000FF' },
      variable: { fg: '#FFFFFF' },
      success: { fg: '#00FF00' },
      warning: { fg: '#FFFF00' },
      error: { fg: '#FF0000' },
      info: { fg: '#0000FF' },
      statusIdle: { fg: '#808080' },
      statusReasoning: { fg: '#00FFFF' },
      statusActing: { fg: '#00FF00' },
      statusObserving: { fg: '#0000FF' },
      statusInterrupted: { fg: '#FFFF00' },
      borderColor: { fg: '#808080' },
      wizardTitle: { fg: '#00FFFF' },
      wizardAccent: { fg: '#0000FF' },
      paramDescription: { fg: '#808080' },
      diffAddLine: { bg: '#008000', fg: '#FFFFFF' },
      diffRemoveLine: { bg: '#800000', fg: '#FFFFFF' },
    },
  },
  'light-ansi': {
    name: 'Light ANSI',
    supportsFullColor: false,
    colors: {
      headerBg: { bg: '#FFFFFF', fg: '#000000' },
      headerText: { fg: '#000000' },
      footerBg: { bg: '#FFFFFF' },
      footerText: { fg: '#808080' },
      inputPrompt: { fg: '#0000FF' },
      inputText: { fg: '#000000' },
      autocompleteBg: { bg: '#FFFFFF' },
      autocompleteText: { fg: '#000000' },
      autocompleteSelectedBg: { bg: '#0000FF', fg: '#FFFFFF' },
      autocompleteSelectedText: { fg: '#FFFFFF' },
      autocompleteHeaderText: { fg: '#0000FF', bold: true },
      autocompleteFooterText: { fg: '#808080' },
      autocompleteMoreIndicator: { fg: '#808080' },
      modePlan: { fg: '#0000FF' },
      modeAct: { fg: '#00FF00' },
      modeDiscuss: { fg: '#FF00FF' },
      userMessage: { fg: '#00FF00' },
      assistantMessage: { fg: '#0000FF' },
      systemMessage: { fg: '#FFFF00' },
      keyword: { fg: '#FF00FF' },
      string: { fg: '#00FF00' },
      number: { fg: '#FF0000' },
      comment: { fg: '#808080' },
      function: { fg: '#0000FF' },
      variable: { fg: '#000000' },
      success: { fg: '#00FF00' },
      warning: { fg: '#FFFF00' },
      error: { fg: '#FF0000' },
      info: { fg: '#0000FF' },
      statusIdle: { fg: '#808080' },
      statusReasoning: { fg: '#0000FF' },
      statusActing: { fg: '#00FF00' },
      statusObserving: { fg: '#0000FF' },
      statusInterrupted: { fg: '#FFFF00' },
      borderColor: { fg: '#808080' },
      wizardTitle: { fg: '#0000FF' },
      wizardAccent: { fg: '#0000FF' },
      paramDescription: { fg: '#808080' },
      diffAddLine: { bg: '#90EE90', fg: '#000000' },
      diffRemoveLine: { bg: '#FFB6C1', fg: '#000000' },
    },
  },
};
